name: Update ICS Calendar

on:
  schedule:
    - cron: '0 */6 * * *'  # Alle 6 Stunden
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install ics requests

    - name: Run calendar merge script
      run: python kalender_merge.py

    - name: Commit and push updated ICS
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/zentral.ics
        git commit -m "Update zentral.ics" || echo "Keine Änderungen"
        git push
